
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arshnoor Singh
 */
public class icon extends javax.swing.JFrame {

    /**
     * Creates new form icon
     */
    public icon() {
        initComponents();
        this.setSize(650,525);
        this.setLocation(150,120);
        this.setResizable(false);
        try{  Image scaledimage2 = ImageIO.read(new File("C:\\Users\\Arshnoor Singh\\Desktop\\New folder\\5fa3c5af3918f6ac8dc699d16e52f528--material-design-diagonal (1).jpg  ")).getScaledInstance(lbback.getWidth(), lbback.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon img2 = new ImageIcon(scaledimage2);
            lbback.setIcon(img2);}
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btclient = new javax.swing.JButton();
        btadmin = new javax.swing.JButton();
        lbback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btclient.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        btclient.setText("Client");
        btclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclientActionPerformed(evt);
            }
        });
        getContentPane().add(btclient);
        btclient.setBounds(90, 230, 428, 142);

        btadmin.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        btadmin.setText("admin");
        btadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btadminActionPerformed(evt);
            }
        });
        getContentPane().add(btadmin);
        btadmin.setBounds(93, 41, 428, 142);
        getContentPane().add(lbback);
        lbback.setBounds(0, 0, 670, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btadminActionPerformed
      Admin1 ad=new Admin1();
      ad.setVisible(true);
      
    }//GEN-LAST:event_btadminActionPerformed

    private void btclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclientActionPerformed
       Client cl=new Client();
       cl.setVisible(true);
    }//GEN-LAST:event_btclientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(icon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(icon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(icon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(icon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new icon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadmin;
    private javax.swing.JButton btclient;
    private javax.swing.JLabel lbback;
    // End of variables declaration//GEN-END:variables
}
