/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hardeep
 */
public class SingleImage extends javax.swing.JPanel {

    /**
     * Creates new form SingleImage
     */
    public SingleImage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImage = new javax.swing.JLabel();

        setLayout(null);

        lbImage.setText("jLabel1");
        add(lbImage);
        lbImage.setBounds(0, 0, 290, 140);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lbImage;
    // End of variables declaration//GEN-END:variables
}
